language: node_js
node_js:
  - "8"
notifications:
  email: false
cache:
  yarn: true
  directories:
    - "node_modules"
    - ~/.npm
cache:
  directories:
    - "node_modules"
after_success:
  - test $TRAVIS_BRANCH = "master" && npm run semantic-release